
CMD_MOD = \
	../Lesson-25/mycp.c	\
	../Lesson-26/readelf.c	\
	../Lesson-27/sed.c	\
	../Lesson-28/cmd_math.c \
	../Lesson-29/cmd_more.c	\
	../Lesson-30/cmd_sort.c	

all:
	gcc shell.c $(CMD_MOD) -o bashclone


